CREATE TABLE votes (
    id SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL,
    ideaId INTEGER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (userId, ideaId),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (ideaId) REFERENCES ideas(id) ON DELETE CASCADE
);